"""add exam structure

Revision ID: 8c6f02a5628a
Revises: 011f65d805a5
Create Date: 2021-10-21 09:36:33.476582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6f02a5628a'
down_revision = '011f65d805a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('material', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('exam', sa.Column('level', sa.String(length=64), nullable=True))
    op.add_column('question', sa.Column('exercise_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'exercise', ['exercise_id'], ['id'])
    op.drop_column('question', 'exam')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('exam', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'exam', ['exam'], ['id'])
    op.drop_column('question', 'exercise_id')
    op.drop_column('exam', 'level')
    op.drop_table('exercise')
    op.drop_table('paper')
    # ### end Alembic commands ###
